"""Run the private API, the public web server and (optionally) the Slack bot together.

API and web are required: if either exits, the container stops. The Slack bot
(calendar → DM → recording approval) runs only when SLACK_BOT_TOKEN and SLACK_APP_TOKEN
are set, and is restarted on its own if it crashes.

Backups (#85): with LITESTREAM_BUCKET and its keys set, the SQLite database is restored from
object storage before the API starts and then replicated continuously by Litestream. A failed
restore stops the container instead of starting empty — an empty database would be replicated
over the backup.
"""
import collections
import json
import os
import signal
import subprocess
import sys
import threading
import time
import urllib.request


_PROVIDER_SECRETS = ("ANTHROPIC_API_KEY", "GEMINI_API_KEY", "GROQ_API_KEY", "OPENAI_API_KEY",
                     "ADMIN_PASSWORD", "WORKSPACE_PASSWORD",
                     # Atlassian (#82): only the backend searches and creates issues/pages
                     "ATLASSIAN_API_TOKEN", "JIRA_API_TOKEN", "CONFLUENCE_API_TOKEN")


_BACKUP_SECRETS = ("LITESTREAM_ACCESS_KEY_ID", "LITESTREAM_SECRET_ACCESS_KEY")
_BACKUP_CONFIG = "/tmp/litestream.yml"


def _env_without(names):
    return {key: value for key, value in os.environ.items() if key not in names}


def _bot_env():
    env = _env_without(_PROVIDER_SECRETS + _BACKUP_SECRETS + ("BACKEND_API_KEY",))
    public_url = os.environ.get("PUBLIC_URL") or os.environ.get("RENDER_EXTERNAL_URL", "")
    env.update(
        PORT="3005",  # internal only (Microsoft sign-in routes); the platform routes just $PORT
        BACKEND_URL="http://127.0.0.1:8000",
        RECORDING_PAGE_URL=public_url or "http://localhost:" + os.environ.get("PORT", "7860"),
        ALERT_STORE_PATH="/app/data/sent_alerts.json",
    )
    return env


def _database_path():
    return os.path.join(os.environ.get("STORAGE_DIR", "/app/data/recordings"), "workspace.sqlite3")


def backup_enabled():
    return all(os.environ.get(name) for name in ("LITESTREAM_BUCKET",) + _BACKUP_SECRETS)


def write_backup_config(path=_BACKUP_CONFIG):
    """Litestream config without secrets — it reads LITESTREAM_ACCESS_KEY_ID/SECRET from the env."""
    replica = {"type": "s3", "bucket": os.environ["LITESTREAM_BUCKET"],
               "path": os.environ.get("LITESTREAM_PATH") or "meeting-automation"}
    for key in ("endpoint", "region"):
        value = os.environ.get(f"LITESTREAM_{key.upper()}")
        if value:
            replica[key] = value
    lines = [
        "# Generated by start.py",
        "snapshot:",
        "  interval: 24h",
        # How far back a point-in-time restore can go.
        f"  retention: {json.dumps(os.environ.get('LITESTREAM_RETENTION') or '168h')}",
        "dbs:",
        f"  - path: {json.dumps(_database_path())}",
        "    replica:",
        *(f"      {key}: {json.dumps(value)}" for key, value in replica.items()),
    ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return path


def alert(text):
    """Best effort: admin Slack channel (MONITOR_ALERT_CHANNEL) and the platform log."""
    print(f"alert: {text}", file=sys.stderr)
    token, channel = os.environ.get("SLACK_BOT_TOKEN"), os.environ.get("MONITOR_ALERT_CHANNEL")
    if not (token and channel):
        return
    request = urllib.request.Request(
        "https://slack.com/api/chat.postMessage",
        data=json.dumps({"channel": channel, "text": f"🚨 *[서버 경고]* {text}"}).encode(),
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json; charset=utf-8"},
    )
    try:
        urllib.request.urlopen(request, timeout=10).close()
    except OSError as exc:
        print(f"warning: alert not delivered: {exc}", file=sys.stderr)


def restore_database(config):
    """Restore from the backup when the local database is missing (fresh container)."""
    database = _database_path()
    if os.path.exists(database):
        print("info: backup on — keeping the existing database", file=sys.stderr)
        return "kept"
    os.makedirs(os.path.dirname(database), exist_ok=True)
    try:
        result = subprocess.run(["litestream", "restore", "-config", config, "-if-db-not-exists",
                                 "-if-replica-exists", database], timeout=300)
        failed = result.returncode != 0
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"error: litestream restore: {exc}", file=sys.stderr)
        failed = True
    if failed:
        alert("백업에서 데이터베이스를 복원하지 못해 서버를 시작하지 않았습니다. 백업 저장소 주소·키를 확인하세요.")
        raise RuntimeError("Backup restore failed — refusing to start with an empty database")
    restored = os.path.exists(database)
    print(f"info: backup on — {'restored the database from backup' if restored else 'no backup yet, starting fresh'}",
          file=sys.stderr)
    return "restored" if restored else "fresh"


class Supervised:
    """A helper process restarted with backoff; alerts once an hour if it keeps crashing."""

    def __init__(self, name, command, env=None, cwd=None, alert_text=None):
        self.name, self.command, self.env, self.cwd, self.alert_text = name, command, env, cwd, alert_text
        self.process = None
        self.backoff = 5.0
        self.next_start = 0.0
        self.crashes = collections.deque(maxlen=3)
        self.last_alert = float("-inf")

    def tick(self, now):
        if self.process is not None and self.process.poll() is None:
            return
        if now < self.next_start:
            return
        if self.process is not None:
            print(f"warning: {self.name} exited ({self.process.returncode}); restarting", file=sys.stderr)
            self.backoff = min(self.backoff * 2, 300.0)
            self.crashes.append(now)
            if (self.alert_text and len(self.crashes) == 3 and now - self.crashes[0] < 600
                    and now - self.last_alert > 3600):
                self.last_alert = now
                alert(self.alert_text)
        self.process = subprocess.Popen(self.command, cwd=self.cwd, env=self.env)
        self.next_start = now + self.backoff


def main():
    provider = os.environ.get("LLM_PROVIDER", "").lower() or (
        "gemini" if os.environ.get("GEMINI_API_KEY") else "anthropic")
    llm_key = "GEMINI_API_KEY" if provider == "gemini" else "ANTHROPIC_API_KEY"
    for name in ("BACKEND_API_KEY", llm_key):
        if not os.environ.get(name):
            raise RuntimeError(f"Missing required secret: {name}")
    if not (os.environ.get("ADMIN_PASSWORD") or os.environ.get("WORKSPACE_PASSWORD")):
        print("warning: ADMIN_PASSWORD not set — startup fails unless users already exist", file=sys.stderr)
    stopped = threading.Event()
    signal.signal(signal.SIGTERM, lambda *_: stopped.set())
    signal.signal(signal.SIGINT, lambda *_: stopped.set())
    backup = None
    if backup_enabled():
        config = write_backup_config()
        restore_database(config)
        backup = Supervised("litestream", ["litestream", "replicate", "-config", config],
                            alert_text="백업(Litestream)이 반복해서 멈추고 있습니다. 백업 저장소 상태·키를 확인하세요.")
    else:
        print("info: backup disabled (set LITESTREAM_BUCKET and its keys to enable)", file=sys.stderr)
    children = []
    bot = None
    try:
        api = subprocess.Popen(
            [sys.executable, "-m", "uvicorn", "app.main:app", "--host", "127.0.0.1", "--port", "8000"],
            cwd="/app/backend", env=_env_without(_BACKUP_SECRETS),
        )
        children.append(api)
        deadline = time.monotonic() + 60
        while True:
            if stopped.is_set():
                return 0
            if api.poll() is not None:
                raise RuntimeError("Backend exited before becoming ready")
            try:
                with urllib.request.urlopen("http://127.0.0.1:8000/health", timeout=2) as res:
                    if res.status == 200:
                        break
            except OSError:
                pass
            if time.monotonic() > deadline:
                raise RuntimeError("Backend startup timed out")
            stopped.wait(1)
        web_env = _env_without(_PROVIDER_SECRETS + _BACKUP_SECRETS + ("SLACK_BOT_TOKEN", "SLACK_APP_TOKEN",
                                                                      "CALENDAR_ICS_URLS", "AZURE_CLIENT_SECRET"))
        # Render/Cloud Run inject PORT; Hugging Face uses the fixed app_port 7860.
        web_env.update(PORT=os.environ.get("PORT", "7860"), HOSTNAME="0.0.0.0")
        if backup:
            web_env["WORKSPACE_STORAGE"] = "replicated"  # hides the "data is wiped on restart" banner
        children.append(subprocess.Popen(["node", "server.js"], cwd="/app/frontend", env=web_env))

        bot = None
        if os.environ.get("SLACK_BOT_TOKEN") and os.environ.get("SLACK_APP_TOKEN"):
            bot = Supervised("Slack bot", ["node", "src/app.js"], env=_bot_env(), cwd="/app/slack-bot")
        else:
            print("info: Slack bot disabled (set SLACK_BOT_TOKEN and SLACK_APP_TOKEN to enable)", file=sys.stderr)
        while True:
            now = time.monotonic()
            if backup:
                backup.tick(now)
            if bot:
                bot.tick(now)
            if stopped.wait(1):
                break
            if any(child.poll() is not None for child in children):
                return 1
        return 0
    finally:
        if bot and bot.process is not None:
            children.append(bot.process)
        for child in children:
            if child.poll() is None:
                child.terminate()
        for child in children:
            _wait(child, 15)
        # Last, so the final writes of the API are synced to the backup before exit.
        if backup and backup.process is not None and backup.process.poll() is None:
            backup.process.terminate()
            _wait(backup.process, 20)


def _wait(process, timeout):
    try:
        process.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait()


if __name__ == "__main__":
    sys.exit(main())
